#!/usr/bin/env bash
rm -rf ./dist
mkdir dist
pandoc --standalone --embed-resources --template template.html content/index.md -o dist/index.html
pandoc --standalone --embed-resources --template template-happy.html content/haircut-volunteer.md -o dist/haircut-volunteer.html
