name: build and publish on push
run-name: rebuild and publish after ${{ github.actor }}'s commit'
on: 
  push:
    branches:
      - 'deploy'

jobs:
  build-and-deploy:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: deploy

      - uses: r-lib/actions/setup-pandoc@v2
      
      - run: echo "${{secrets.CF_API_TOKEN}}"

      - name: Build
        run: ./build

      - name: Publish
        uses: Cyb3r-Jak3/wrangler-action
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'dist'
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          # shell: pages publish ./dist 
    
